### ISSUE TITLE
[vite:vue] Failed to resolve vue/compiler-sfc.

### ISSUE THREAD

**Issue by ydy4** [mitre/magma#64]
i run caldera with python3 server.py --insecure --build, then i get the error for vue 
[vite:vue] Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
error during build:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (/home/ydy/caldera/plugins/magma/node_modules/@vitejs/plugin-vue/dist/index.js:3955:11)
    at Object.buildStart (/home/ydy/caldera/plugins/magma/node_modules/@vitejs/plugin-vue/dist/index.js:4686:46)
    at /home/ydy/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:22834:37
    at async Promise.all (index 4)
    at async /home/ydy/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23622:13
    at async catchUnfinishedHookActions (/home/ydy/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23132:20)
    at async rollupInternal (/home/ydy/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23620:5)
    at async doBuild (/home/ydy/caldera/plugins/magma/node_modules/vite/dist/node/chunks/dep-689425f3.js:41710:24)
    at async build (/home/ydy/caldera/plugins/magma/node_modules/vite/dist/node/chunks/dep-689425f3.js:41552:16)
    at async CAC.<anonymous> (/home/ydy/caldera/plugins/magma/node_modules/vite/dist/node/cli.js:738:9)
 
![image](https://github.com/user-attachments/assets/c9f8c4b7-c569-4fe3-8ea5-00258eaa061d)

**Comment by elegantmoose** [comment]
Is nodejs v16 or greater installed?

**Comment by ydy4** [comment]
> Is nodejs v16 or greater installed?

I updated the nodejs and it worked
